"""Dashboard endpoint — aggregated view for the homepage."""

from fastapi import APIRouter

from api.services.athena_client import query_athena

router = APIRouter()


@router.get("")
async def get_dashboard():
    """
    Returns homepage data:
    - Top signals today
    - Market summary (sector performance)
    - Upcoming earnings this week
    - Risk alerts
    """
    # Top opportunities (stocks with highest composite scores today)
    opportunities = await query_athena("""
        SELECT symbol, exchange, composite_score, verdict, top_signals, sector
        FROM opportunities
        WHERE date = (SELECT MAX(date) FROM opportunities)
        ORDER BY composite_score DESC
        LIMIT 10
    """)

    # Sector performance (avg price change by sector today)
    # This would need company_profiles joined with stocks
    # Simplified: return top signals for now

    return {
        "top_opportunities": opportunities,
        "market_summary": {},
        "earnings_this_week": [],
        "risk_alerts": [],
    }


@router.get("/morning-brief")
async def get_morning_brief():
    """
    AI-generated morning brief summarizing overnight market activity.
    Placeholder — will integrate with Bedrock Claude later.
    """
    return {
        "brief": "Morning brief will be generated by AI based on overnight signals, news sentiment, and price movements.",
        "generated_at": None,
    }
